### ISSUE TITLE
Use `bufferWrap` to support `ArrayBuffer`, `Uint8Array` and `Buffer`

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/js-db#3]
### Specification

The `ArrayBuffer` type is more generalised in the JS ecosystem. The DB right now focuses on taking Node Buffers.

Node buffers can be converted to `ArrayBuffer` easily, and `ArrayBuffer` can be wrapped in Node buffers.

According to this comment: https://github.com/Level/level-js/issues/34#issuecomment-397811192 it is possible to use ArrayBuffers directly in leveldb, it just not documented.

It says that the `asBuffer` has to be turned false.

I'm not sure how this would work with `keyEncoding` and `valueEncoding` that we have set to `'binary'`.

Our `raw` is also specifying that we would get `Buffer`, would that mean we instead say that we return `ArrayBuffer` instead, and with keys it would be `string | ArrayBuffer`?

Furthermore this would impact js-encryptedfs, so it's worthwhile to explore the implications of this.

The primary reason to do this would be cross-platform compatibility for mobile platforms that may not have the Node buffer.

The alternative would be use https://github.com/feross/buffer everywhere as a dependency so that way everything just uses the `buffer` library. This will mean that any usage of  `import { Buffer } from 'buffer';` will be resolved by feross/buffer first though, so one should beware of that.

**Note that all Node `Buffer` is `Uint8Array` which is `ArrayBuffer`.**

**If something supports `ArrayBuffer`, they would support `Uint8Array` and `Buffer` at the same time.**

One benefit would be integration of js-id https://github.com/MatrixAI/js-id/issues/1 can be simplified since `Id` as `Uint8Array` can be stored directly in the DB without first wrapping them as `Buffer`.

### Additional context

* https://github.com/Level/level-js/issues/34#issuecomment-397811192

### Tasks

1. [x] - Investigate `ArrayBuffer` compatibility in leveldb
2. [x] - Investigate to what extent can we enable compatibility with `ArrayBuffer` in DB without losing `Buffer` support
3. [ ] - Replace all uses of `string | Buffer` with `string | ArrayBuffer` for keys, but retain `Buffer` on returned output.
   * fix `domainPath` with https://github.com/MatrixAI/js-db/issues/3#issuecomment-946416685
   * this incorporates the Robustness principle: https://en.wikipedia.org/wiki/Robustness_principle
4. [ ] - Change `this.crypto.key` to be assumed to be `ArrayBuffer`
5. [ ] - Change `toArrayBuffer` to an explicit slice copy of all possible instances of `ArrayBuffer` type
6. [ ] - The `fromArrayBuffer` is still useful since we return `Buffer`.
7. [ ] - Change `serialize` and `deserialize` to use `ArrayBuffer` and `TextEncoder` and `TextDecoder` which can do the `utf-8` encoding/decoding.
8. [ ] - Check if PK is using any of the utility functions here, some uses of `deserialize` and `serialize` might need to change.
9. [ ] - Ensure that most signatures are still compatible
10. [ ] - Update all tests to include `Uint8Array` and `ArrayBuffer` usage, and ensure that slice-copying is working.
11. [ ] - Check that there's no performance regression on the benchmarks

**Comment by CMCDragonkai** [comment]
Note that node module resolution would load locally first before loading from anywhere else.

I'm not sure how this applies to non-node runtimes like in NativeScript. Recommend not doing anything here until we have understood the platform properly.

The usage of `ArrayBuffer` would be a standardisation across other JS libraries and anything claiming to support ecmascript remember.

**Comment by CMCDragonkai** [comment]
The only issue would be the `domainPath` that uses `prefixer`. Does that work with just `ArrayBuffer`, or would that need `Uint8Array`?

**Comment by CMCDragonkai** [comment]
No it doesn't because it uses `Buffer.isBuffer` to check. It throws this error `Error: key should be a string or a buffer` if it is not `Buffer`.

However one could wrap it in our `domainPath` function. We should be able to zero-copy it into a Node `Buffer`.

**Comment by CMCDragonkai** [comment]
The `TextDecoder` works on `ArrayBuffer` and `Uint8Array`.

```
[nix-shell:~/Projects/js-db]$ node
Welcome to Node.js v14.17.3.
Type ".help" for more information.
> u = new Uint8Array([0x61, 0x62, 0x63])
Uint8Array(3) [ 97, 98, 99 ]
> u.buffer
ArrayBuffer { [Uint8Contents]: <61 62 63>, byteLength: 3 }
> new TextDecoder().decode(u.buffer)
'abc'
> new TextDecoder().decode(u)
'abc'```

**Comment by CMCDragonkai** [comment]
Need to ensure that this doesn't result in a performance regression with respect to benchmarks.

**Comment by CMCDragonkai** [comment]
https://github.com/Level/subleveldown/issues/111 - seems like we should be able to use `Buffer`, further checking required.

**Comment by CMCDragonkai** [comment]
This is somewhat more complicated now that we have alot of functions relying on the `Buffer` interface.

Applications that use this library right now has to use the feross buffer package if their runtime environment doesn't have the `Buffer` class.

Having an `ArrayBuffer` compatible system should make this alot more compatible, however unless this package is made generic over the underlying DB, that is browser indexeddb or node leveldb, then doing this doesn't really change the portability alot. However it does enable the usage of our system to be bit easier, so that when downstream libraries like PK uses `ArrayBuffer`, they don't need to convert it to a `Buffer` just so that it can be work inside the DB.

Although the new abstract-level has support for Uint8Array, so that may be a better way to support it https://github.com/Level/browser-level/blob/98c13d4356fdb6ca5668ddd35859e6c9b326b5cb/UPGRADING.md#uint8array-support rather than directly supporting `ArrayBuffer`.

**Comment by CMCDragonkai** [comment]
We are no longer attached to `abstract-level` anymore. We are directly using `rocksdb`. As it forces the NAPI API, we might as well stick with buffer. Any need to use `ArrayBuffer` should just use the feross buffer.

The `js-db` will likely have native mobile bindings later, in which case even there I'd say we should continue using feross buffer. The `ArrayBuffer`is just quite low level.

One way to quickly solve this issue is to just take `ArrayBuffer` type, and if it is an array buffer, wrap it up as a `Buffer` automatically. That way it avoids users having to wrap it themselves.

**Comment by CMCDragonkai** [comment]
If we receive an `ArrayBuffer`. All we need to do is `Buffer.from(arrayBuffer)`. That's it. That will be zero-copy and just wrap the buffer.

If we use `bufferWrap` as in Polykey, then we can also support `Uint8Array`.

So let's just do that. Here's the `bufferWrap` function.

```ts
/**
 * Zero-copy wraps ArrayBuffer-like objects into Buffer
 * This supports ArrayBuffer, TypedArrays and the NodeJS Buffer
 */
function bufferWrap(
  array: BufferSource,
  offset?: number,
  length?: number,
): Buffer {
  if (Buffer.isBuffer(array)) {
    return array;
  } else if (ArrayBuffer.isView(array)) {
    return Buffer.from(
      array.buffer,
      offset ?? array.byteOffset,
      length ?? array.byteLength,
    );
  } else {
    return Buffer.from(array, offset, length);
  }
}
```

**Comment by CMCDragonkai** [comment]
This means when we are passing Ids into the DB, we no longer have to do `const idBuffer = id.toBuffer();`.

**Comment by CMCDragonkai** [comment]
@amydevs Since in js-db we are planning to continue using `Buffer`, you can use it in `js-ws` as well, and just wrap your `ArrayBuffer` as a regular buffer.

Do this: https://github.com/MatrixAI/js-db/issues/3#issuecomment-1280289006 when you check `instanceof ArrayBuffer`.

**Comment by CMCDragonkai** [comment]
Actually for `js-ws` it makes more sense to always convert to `Uint8Array` and not deal with node buffers.

So that means if it is an `ArrayBuffer`, you can do `new Uint8Array(ab)`. If it is node buffer... it is already a `Uint8Array`.
